// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetImages():Promise<Array<types.ImageInfo>>;

export function GetKnownScreens():Promise<Array<types.Screen>>;

export function Restart():Promise<void>;

export function SetImage(arg1:string,arg2:string):Promise<void>;

export function UpdateScreens(arg1:Array<types.Screen>):Promise<void>;
