// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImages() {
  return window['go']['main']['App']['GetImages']();
}

export function GetKnownScreens() {
  return window['go']['main']['App']['GetKnownScreens']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SetImage(arg1, arg2) {
  return window['go']['main']['App']['SetImage'](arg1, arg2);
}

export function UpdateScreens(arg1) {
  return window['go']['main']['App']['UpdateScreens'](arg1);
}
