// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {images} from '../models';

export function GetImages():Promise<Array<images.ImageInfo>>;

export function IsWallpaperExist(arg1:string):Promise<boolean>;

export function Restart():Promise<void>;

export function SaveWallpaper(arg1:string,arg2:string):Promise<string>;

export function SetImage(arg1:string,arg2:string):Promise<void>;

export function SetWallpaper(arg1:string):Promise<void>;
