// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImages() {
  return window['go']['main']['App']['GetImages']();
}

export function IsWallpaperExist(arg1) {
  return window['go']['main']['App']['IsWallpaperExist'](arg1);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SaveWallpaper(arg1, arg2) {
  return window['go']['main']['App']['SaveWallpaper'](arg1, arg2);
}

export function SetImage(arg1, arg2) {
  return window['go']['main']['App']['SetImage'](arg1, arg2);
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}
